const expres                    =   require('express')
const router                    =   expres.Router()
const authorization             =   require('../middleware/authentication')

// const CommonController          =  require('../controllers/Common.js')
// const upload = require('../middleware/fileUpload')
// router.post("/Common/Upload",upload.single("singleFile"),CommonController.Upload)

const UserController          =  require('../controllers/User.js')
router.post("/User/create",UserController.create)
router.get("/User/list",UserController.list)
router.get("/User/view/:id",authorization,UserController.view)
router.patch("/User/update/:id",authorization,UserController.update)
router.post("/User/login",UserController.login)
router.post("/User/resendotp",  UserController.login)
router.post("/User/loginwithotp",UserController.loginwithotp)
router.get("/User/refreshToken/:refreshToken",UserController.refreshToken)
// router.delete("/User/delete/:id",UserController.remove)
// router.delete("/User/bulkdelete/:ids",UserController.bulkremove)
// router.get("/User/forgotpassword/:email", UserController.forgotpassword)
// router.patch("/User/resetpassword/:id/:resetPawordToken",UserController.resetpassword)
// router.post("/User/changePassword",UserController.changePassword)

const UserInterestController          =  require('../controllers/UserInterest.js')
router.post("/UserInterest/create",authorization,UserInterestController.create)
router.get("/UserInterest/list",authorization,UserInterestController.list)
router.get("/UserInterest/view/:id",authorization,UserInterestController.view)
// router.patch("/UserInterest/update/:id",authorization,UserInterestController.update)
router.delete("/UserInterest/delete/:id",authorization,UserInterestController.remove)
router.delete("/UserInterest/bulkdelete/:ids",authorization,UserInterestController.bulkremove)

const GroupController          =  require('../controllers/Group.js')
router.post("/Group/create",authorization,GroupController.create)
router.get("/Group/list",authorization,GroupController.list)
router.get("/Group/view/:id",authorization,GroupController.view)
router.patch("/Group/update/:id",authorization,GroupController.update)
router.delete("/Group/delete/:id",authorization,GroupController.remove)
router.delete("/Group/bulkdelete/:ids",authorization,GroupController.bulkremove)

const ActivityController          =  require('../controllers/Activity.js')
router.post("/Activity/create",authorization,ActivityController.create)
router.get("/Activity/list",authorization,ActivityController.list)
router.get("/Activity/view/:id",authorization,ActivityController.view)
// router.patch("/Activity/update/:id",authorization,ActivityController.update)
router.delete("/Activity/delete/:id",authorization,ActivityController.remove)
router.delete("/Activity/bulkdelete/:ids",authorization,ActivityController.bulkremove)

const ActivityUserController          =  require('../controllers/ActivityUser.js')
// router.post("/ActivityUser/create",authorization,ActivityUserController.create)
router.get("/ActivityUser/list",authorization,ActivityUserController.list)
router.get("/ActivityUser/view/:id",authorization,ActivityUserController.view)
// router.patch("/ActivityUser/update/:id",authorization,ActivityController.update)
router.delete("/ActivityUser/delete/:id",authorization,ActivityUserController.remove)
router.delete("/ActivityUser/bulkdelete/:ids",authorization,ActivityUserController.bulkremove)

const MasterActivityController          =  require('../controllers/MasterActivity.js')
router.post("/MasterActivity/create",authorization,MasterActivityController.create)
router.get("/MasterActivity/list",authorization,MasterActivityController.list)
router.get("/MasterActivity/view/:id",authorization,MasterActivityController.view)
router.patch("/MasterActivity/update/:id",authorization,MasterActivityController.update)
router.delete("/MasterActivity/delete/:id",authorization,MasterActivityController.remove)
router.delete("/MasterActivity/bulkdelete/:ids",authorization,MasterActivityController.bulkremove)

const MasterIndustryController          =  require('../controllers/MasterIndustry.js')
router.post("/MasterIndustry/create",authorization,MasterIndustryController.create)
router.get("/MasterIndustry/list",authorization,MasterIndustryController.list)
router.get("/MasterIndustry/view/:id",authorization,MasterIndustryController.view)
router.patch("/MasterIndustry/update/:id",authorization,MasterIndustryController.update)
router.delete("/MasterIndustry/delete/:id",authorization,MasterIndustryController.remove)
router.delete("/MasterIndustry/bulkdelete/:ids",authorization,MasterIndustryController.bulkremove)

const MasterInterestController          =  require('../controllers/MasterInterest.js')
router.post("/MasterInterest/create",authorization,MasterInterestController.create)
router.get("/MasterInterest/list",authorization,MasterInterestController.list)
router.get("/MasterInterest/view/:id",authorization,MasterInterestController.view)
router.patch("/MasterInterest/update/:id",authorization,MasterInterestController.update)
router.delete("/MasterInterest/delete/:id",authorization,MasterInterestController.remove)
router.delete("/MasterInterest/bulkdelete/:ids",authorization,MasterInterestController.bulkremove)

const MasterProfessionController          =  require('../controllers/MasterProfession.js')
router.post("/MasterProfession/create",authorization,MasterProfessionController.create)
router.get("/MasterProfession/list",authorization,MasterProfessionController.list)
router.get("/MasterProfession/view/:id",authorization,MasterProfessionController.view)
router.patch("/MasterProfession/update/:id",authorization,MasterProfessionController.update)
router.delete("/MasterProfession/delete/:id",authorization,MasterProfessionController.remove)
router.delete("/MasterProfession/bulkdelete/:ids",authorization,MasterProfessionController.bulkremove)

module.exports = router